/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import codigoEscambot.Usuario;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import model.dao.UsuarioDAO;

public class TelaAlterarDadosUsuario extends javax.swing.JFrame {
    
    /**
     * Creates new form telaLogin
     */
    public TelaAlterarDadosUsuario() {
        initComponents();
        readJTable();
        
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();

        for (Usuario u : udao.read()) {

            modelo.addRow(new Object[]{
                u.getIdUsuario(),
                u.getSenha(),
                u.getLogin(),
                u.getNome(),
                u.getData(),
                u.getCpf(),
                u.getCidade(),
                u.getTelefone()
            });

        }

    }
    public void readJTableForNome(String nome) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();

        for (Usuario u : udao.readNome(nome)) {

            modelo.addRow(new Object[]{
                u.getIdUsuario(),
                u.getSenha(),
                u.getLogin(),
                u.getNome(),
                u.getData(),
                u.getCpf(),
                u.getCidade(),
                u.getTelefone()
            });

        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPTelaAlterarDados = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFmtDataNascimento = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jFmtCPF = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jCBEstados = new javax.swing.JComboBox<>();
        jLabelTelefone = new javax.swing.JLabel();
        jFmtTelefone = new javax.swing.JFormattedTextField();
        jLabelLogin = new javax.swing.JLabel();
        txtLoginC = new javax.swing.JTextField();
        jLabelAntigaSenha = new javax.swing.JLabel();
        jLabelNovaSenha = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JPasswordField();
        ButCancelar = new javax.swing.JButton();
        txtSenhaAntiga = new javax.swing.JPasswordField();
        ButSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButCancelar1 = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        Busca = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar dados");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_transparent.png")).getImage());
        setResizable(false);

        jPTelaAlterarDados.setBackground(new java.awt.Color(106, 97, 87));
        jPTelaAlterarDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela de alteração dos dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(10, 3, 3))); // NOI18N

        jLabelNome.setForeground(new java.awt.Color(20, 10, 10));
        jLabelNome.setText("Novo nome");

        txtNome.setToolTipText("Digite um novo nome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabelDataNascimento.setForeground(new java.awt.Color(20, 10, 10));
        jLabelDataNascimento.setText("Nova data de nascimento");

        jFmtDataNascimento.setToolTipText("Digite um novo nome");
        jFmtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNascimentoActionPerformed(evt);
            }
        });

        jLabelCPF.setForeground(new java.awt.Color(20, 10, 10));
        jLabelCPF.setText("Novo CPF");

        jFmtCPF.setToolTipText("Digite um novo nome");
        jFmtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCPFActionPerformed(evt);
            }
        });

        jLabelCidade.setForeground(new java.awt.Color(20, 10, 10));
        jLabelCidade.setText("Alterar cidade");

        txtCidade.setToolTipText("Digite uma nova cidade");
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        jLabelEstado.setForeground(new java.awt.Color(20, 10, 10));
        jLabelEstado.setText("Alterar estado");

        jCBEstados.setBackground(new java.awt.Color(92, 92, 79));
        jCBEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu estado", "Acre - AC ", "Alagoas - AL", "Amapá - AP ", "Amazonas - AM", "Bahia - BA", "Ceará - CE ", "Distrito Federal - DF", "Espírito Santo - ES", "Goiás - GO ", "Maranhão - MA ", "Mato Grosso - MT", "Mato Grosso do Sul - MS ", "Minas Gerais - MG", "Pará - PA", "Paraíba - PB ", "Paraná - PR ", "Pernambuco - PE ", "Piauí - PI", "Roraima - RR ", "Rondônia - RO ", "Rio de Janeiro - RJ ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS ", "Santa Catarina - SC ", "São Paulo - SP ", "Sergipe - SE ", "Tocantins - TO" }));
        jCBEstados.setToolTipText("Selecione um novo estado");
        jCBEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadosActionPerformed(evt);
            }
        });

        jLabelTelefone.setForeground(new java.awt.Color(20, 10, 10));
        jLabelTelefone.setText("Novo telefone");

        jFmtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFmtTelefone.setToolTipText("Digite um novo telefone");
        jFmtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtTelefoneActionPerformed(evt);
            }
        });

        jLabelLogin.setForeground(new java.awt.Color(20, 10, 10));
        jLabelLogin.setText("Novo login");

        txtLoginC.setToolTipText("Digite um novo login");
        txtLoginC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginCActionPerformed(evt);
            }
        });

        jLabelAntigaSenha.setForeground(new java.awt.Color(20, 10, 10));
        jLabelAntigaSenha.setText("Antiga senha");

        jLabelNovaSenha.setForeground(new java.awt.Color(20, 10, 10));
        jLabelNovaSenha.setText("Nova senha");

        txtNovaSenha.setToolTipText("Digite uma nova senha");
        txtNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNovaSenhaActionPerformed(evt);
            }
        });

        ButCancelar.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar.setMnemonic('c');
        ButCancelar.setText("Cancelar");
        ButCancelar.setToolTipText("Clique para cancelar a alteração dos dados");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        txtSenhaAntiga.setToolTipText("Digite sua antiga senha");

        ButSalvar.setBackground(new java.awt.Color(234, 234, 27));
        ButSalvar.setMnemonic('s');
        ButSalvar.setText("Salvar");
        ButSalvar.setToolTipText("Clique para salvar");
        ButSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalvarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Usuário", "Senha", "Login", "Nome", "Data de Nascimento", "CPF", "Cidade", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ButCancelar1.setBackground(new java.awt.Color(234, 234, 27));
        ButCancelar1.setMnemonic('c');
        ButCancelar1.setText("Deletar");
        ButCancelar1.setToolTipText("Clique para deletar\n");
        ButCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelar1ActionPerformed(evt);
            }
        });

        Busca.setBackground(new java.awt.Color(92, 92, 79));
        Busca.setMnemonic('c');
        Busca.setText("Busca");
        Busca.setToolTipText("Clique para cancelar a alteração dos dados");
        Busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTelaAlterarDadosLayout = new javax.swing.GroupLayout(jPTelaAlterarDados);
        jPTelaAlterarDados.setLayout(jPTelaAlterarDadosLayout);
        jPTelaAlterarDadosLayout.setHorizontalGroup(
            jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaAlterarDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPTelaAlterarDadosLayout.createSequentialGroup()
                        .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefone)
                            .addComponent(jLabelLogin)
                            .addComponent(jFmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPTelaAlterarDadosLayout.createSequentialGroup()
                                .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLoginC)
                                    .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCPF)
                                        .addComponent(jLabelDataNascimento)
                                        .addComponent(jLabelNome)
                                        .addComponent(jLabelAntigaSenha)
                                        .addGroup(jPTelaAlterarDadosLayout.createSequentialGroup()
                                            .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelCidade)
                                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(157, 157, 157)
                                            .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelEstado)
                                                .addComponent(jCBEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPTelaAlterarDadosLayout.createSequentialGroup()
                                        .addComponent(jLabelNovaSenha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ButCancelar1)
                                        .addGap(18, 18, 18)
                                        .addComponent(ButCancelar))
                                    .addGroup(jPTelaAlterarDadosLayout.createSequentialGroup()
                                        .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPTelaAlterarDadosLayout.createSequentialGroup()
                                                .addComponent(txtNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                                .addGap(16, 16, 16))
                                            .addComponent(txtSenhaAntiga, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButSalvar)
                                    .addComponent(Busca, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jFmtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPTelaAlterarDadosLayout.setVerticalGroup(
            jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaAlterarDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCPF)
                .addGap(1, 1, 1)
                .addComponent(jFmtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAntigaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Busca))
                .addGap(7, 7, 7)
                .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTelaAlterarDadosLayout.createSequentialGroup()
                        .addComponent(jLabelNovaSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPTelaAlterarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButCancelar)
                        .addComponent(ButSalvar)
                        .addComponent(ButCancelar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPTelaAlterarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jPTelaAlterarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        new TelaMenuUsuario().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButCancelarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaSenhaActionPerformed

    private void txtLoginCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginCActionPerformed

    private void jCBEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEstadosActionPerformed

    private void jFmtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtTelefoneActionPerformed

    private void ButSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalvarActionPerformed
        int index = jCBEstados.getSelectedIndex();
        
        if(txtNome.getText().equals("") &
                txtCidade.getText().equals("") & jFmtCPF.getText().equals("   .   .   -  ") & jFmtTelefone.getText().equals("(  )9    -    ") & txtLoginC.getText().equals("") &
                txtSenhaAntiga.getText().equals("") & index == 0 & txtNovaSenha.getText().equals("") & jFmtDataNascimento.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null, "Preencha pelo menos um campo antes de clicar em salvar.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);         
        }else{
            if(!jFmtDataNascimento.getText().equals("")){
                String nova_data = jFmtDataNascimento.getText();
                TelaCadastro.users.get(TelaLogin.indexUser).setData(nova_data);
            }
            if(!txtNome.getText().equals(""))
                TelaCadastro.users.get(TelaLogin.indexUser).setNome(txtNome.getText());
            if(index>=1){
                TelaCadastro.users.get(TelaLogin.indexUser).setEstado(jCBEstados.getSelectedItem().toString());
            }
            if(!jFmtCPF.getText().equals(""))
                TelaCadastro.users.get(TelaLogin.indexUser).setCpf(jFmtCPF.getText());
            if(!txtCidade.getText().equals(""))
                TelaCadastro.users.get(TelaLogin.indexUser).setCidade(txtCidade.getText());
            if(!jFmtTelefone.getText().equals(""))
                TelaCadastro.users.get(TelaLogin.indexUser).setTelefone(jFmtTelefone.getText());
            if(!txtLoginC.getText().equals(""))
                TelaCadastro.users.get(TelaLogin.indexUser).setLogin(txtLoginC.getText());
            
                    JOptionPane.showMessageDialog(null, "Senha e ou dados alterados com sucesso.", "Aviso!",
                JOptionPane.INFORMATION_MESSAGE);
                    String nome = txtNome.getText();
                    String data = jFmtDataNascimento.getText();
                    String cpf = jFmtCPF.getText();
                    String cidade = txtCidade.getText();
                    String estado = jCBEstados.getSelectedItem().toString();
                    String telefone = jFmtTelefone.getText();
                    String senha = txtNovaSenha.getText();
                    String login = txtLoginC.getText();
                    int id = ((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                    Usuario user = new Usuario(cidade, telefone, nome, data, cpf, senha, login, id);
                    UsuarioDAO dao = new UsuarioDAO();
                    dao.update(user);
                    
                
        }
        readJTable();
    }//GEN-LAST:event_ButSalvarActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {

            txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            jFmtDataNascimento.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            jFmtCPF.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            txtCidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            jFmtTelefone.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            txtLoginC.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            txtSenhaAntiga.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void ButCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelar1ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {

            Usuario u = new Usuario();
            UsuarioDAO dao = new UsuarioDAO();

            u.setIdUsuario((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            
            dao.delete(u);

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_ButCancelar1ActionPerformed

    private void BuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaActionPerformed
        // TODO add your handling code here:
        readJTableForNome(txtBusca.getText());
    }//GEN-LAST:event_BuscaActionPerformed

    private void jFmtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataNascimentoActionPerformed

    private void jFmtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarDadosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Busca;
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButCancelar1;
    private javax.swing.JButton ButSalvar;
    private javax.swing.JComboBox<String> jCBEstados;
    private javax.swing.JTextField jFmtCPF;
    private javax.swing.JTextField jFmtDataNascimento;
    private javax.swing.JFormattedTextField jFmtTelefone;
    private javax.swing.JLabel jLabelAntigaSenha;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovaSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPTelaAlterarDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtLoginC;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtNovaSenha;
    private javax.swing.JPasswordField txtSenhaAntiga;
    // End of variables declaration//GEN-END:variables
}
