/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import codigoEscambot.Departamento;
import codigoEscambot.Mercado;
import codigoEscambot.Produto;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.dao.ProdutoDAO;
/**
 *
 * @author thiago
 */
public class TelaAlterarDadosProduto extends javax.swing.JFrame {

    public void carregarTabelaProd(){
        DefaultTableModel modelo = new DefaultTableModel(new Object [] {"Nome","Rating","Tipo"},0);       
        for(int i=0;i<TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.size();i++){
            Object linha[] = new Object[]{TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(i).getNome(), 
                    TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(i).getRating(), TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(i).getTipo()};
            modelo.addRow(linha);
            }
        jTableAlterarDadosP.setModel(modelo);
    }
    public void produtoSelecionado(){
                if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum produto cadastrado.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);   
        }else{
            int index = jTableAlterarDadosP.getSelectedRow();
            if(index>=0){
                txtNomeProduto.setText(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index).getNome());
                txtRating.setText(Integer.toString(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index).getRating()));
                txtTipoProduto.setText(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index).getTipo());
                if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index) instanceof Departamento){   
                    Produto objdep = TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index);
                    Departamento dep = (Departamento) objdep;
                    txtCor.setText(dep.getCor());
                    txtMarca.setText(dep.getMarca());
                    txtUtilidade.setText(dep.getUtilidade());
                    jFmtDataValidade.setEnabled(false);
                }
                if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index) instanceof Mercado){ 
                    jFmtDataValidade.setEnabled(true);
                    Produto objmarket = TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index);
                    Mercado mer = (Mercado)objmarket;
                    txtCor.setText(mer.getCor());
                    txtMarca.setText(mer.getMarca());
                    txtUtilidade.setText(mer.getUtilidade());
                    jFmtDataValidade.setText(mer.getDatadevalidade());
                    
                }           
            }else{
                JOptionPane.showMessageDialog(null, "Selecione um Produto na Tabela ao lado.", "Aviso!",
                    JOptionPane.ERROR_MESSAGE);   
            }
        }
    }
    public TelaAlterarDadosProduto() {
        initComponents();       
        if(!TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.isEmpty())
            carregarTabelaProd();
        
        readJTable();
        
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Mercado p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getIdProduto(),
                p.getNome(),
                p.getRating(),
                p.getTipo(),
                p.getCor(),
                p.getMarca(),
                p.getUtilidade(),
            });

        }

    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTelaAlterarDadosProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipoProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUtilidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmtDataValidade = new javax.swing.JFormattedTextField();
        ButSalvar = new javax.swing.JButton();
        ButCancelar = new javax.swing.JButton();
        jScrollPaneAlterarDadosP = new javax.swing.JScrollPane();
        jTableAlterarDadosP = new javax.swing.JTable();
        ButExcluir = new javax.swing.JButton();
        ButAlterarDados = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButCancelar1 = new javax.swing.JButton();
        ButCancelar2 = new javax.swing.JButton();
        ButCancelar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar dados do produto");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_transparent.png")).getImage());
        setResizable(false);

        jPTelaAlterarDadosProduto.setBackground(new java.awt.Color(106, 97, 87));
        jPTelaAlterarDadosProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela de alterar dados do produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(10, 3, 3))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(20, 10, 10));
        jLabel1.setText("Nome do produto");

        txtNomeProduto.setToolTipText("Digite o nome do produto");
        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(20, 10, 10));
        jLabel2.setText("Rating");

        txtRating.setToolTipText("Digite o rating do produto");
        txtRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatingActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(20, 10, 10));
        jLabel3.setText("Tipo do produto");

        txtTipoProduto.setToolTipText("Digite o tipo do produto");
        txtTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoProdutoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(20, 10, 10));
        jLabel4.setText("Cor do produto");

        txtCor.setToolTipText("Digite a cor do produto");
        txtCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(20, 10, 10));
        jLabel5.setText("Marca do produto");

        txtMarca.setToolTipText("Digite a marca do produto");
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(20, 10, 10));
        jLabel6.setText("Utilidade do produto");

        txtUtilidade.setToolTipText("Digite a utilidade do produto");
        txtUtilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUtilidadeActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(20, 10, 10));
        jLabel7.setText("Data de validade do produto");

        try {
            jFmtDataValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtDataValidade.setToolTipText("Digite a data de validade do produto");
        jFmtDataValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataValidadeActionPerformed(evt);
            }
        });

        ButSalvar.setBackground(new java.awt.Color(234, 234, 27));
        ButSalvar.setMnemonic('s');
        ButSalvar.setText("Salvar");
        ButSalvar.setToolTipText("Clique para salvar");
        ButSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalvarActionPerformed(evt);
            }
        });

        ButCancelar.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar.setMnemonic('c');
        ButCancelar.setText("Cancelar");
        ButCancelar.setToolTipText("Clique para cancelar a ação");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        jScrollPaneAlterarDadosP.setBackground(new java.awt.Color(92, 92, 79));
        jScrollPaneAlterarDadosP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneAlterarDadosP.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableAlterarDadosP.setBackground(new java.awt.Color(92, 92, 79));
        jTableAlterarDadosP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome do produto", "Rating"
            }
        ));
        jTableAlterarDadosP.setGridColor(new java.awt.Color(60, 60, 60));
        jScrollPaneAlterarDadosP.setViewportView(jTableAlterarDadosP);

        ButExcluir.setBackground(new java.awt.Color(234, 234, 27));
        ButExcluir.setMnemonic('e');
        ButExcluir.setText("Excluir");
        ButExcluir.setToolTipText("Clique para excluir o produto selecionado");
        ButExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButExcluirActionPerformed(evt);
            }
        });

        ButAlterarDados.setBackground(new java.awt.Color(92, 92, 79));
        ButAlterarDados.setMnemonic('a');
        ButAlterarDados.setText("Alterar dados");
        ButAlterarDados.setToolTipText("Clique para alterar os dados do produto selecionado");
        ButAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButAlterarDadosActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Produto", "Nome do Produto", "Rating", "Tipo do produto", "Cor ", "Marca", "Utilidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ButCancelar1.setBackground(new java.awt.Color(234, 234, 27));
        ButCancelar1.setMnemonic('c');
        ButCancelar1.setText("Deletar");
        ButCancelar1.setToolTipText("Clique para cancelar o cadastro");
        ButCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelar1ActionPerformed(evt);
            }
        });

        ButCancelar2.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar2.setMnemonic('c');
        ButCancelar2.setText("AtualizarD");
        ButCancelar2.setToolTipText("Clique para cancelar o cadastro");
        ButCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelar2ActionPerformed(evt);
            }
        });

        ButCancelar3.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar3.setMnemonic('c');
        ButCancelar3.setText("AtualizarM");
        ButCancelar3.setToolTipText("Clique para cancelar o cadastro");
        ButCancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTelaAlterarDadosProdutoLayout = new javax.swing.GroupLayout(jPTelaAlterarDadosProduto);
        jPTelaAlterarDadosProduto.setLayout(jPTelaAlterarDadosProdutoLayout);
        jPTelaAlterarDadosProdutoLayout.setHorizontalGroup(
            jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButCancelar3)
                        .addGap(18, 18, 18)
                        .addComponent(ButCancelar2)
                        .addGap(18, 18, 18)
                        .addComponent(ButCancelar1)
                        .addGap(18, 18, 18)
                        .addComponent(ButCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(ButSalvar))
                    .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                        .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                                .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jFmtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                                        .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtUtilidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                                .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTipoProduto, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ButAlterarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ButExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPaneAlterarDadosP, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPTelaAlterarDadosProdutoLayout.setVerticalGroup(
            jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                        .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButAlterarDados))
                        .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPTelaAlterarDadosProdutoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(ButExcluir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUtilidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneAlterarDadosP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPTelaAlterarDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButSalvar)
                    .addComponent(ButCancelar)
                    .addComponent(ButCancelar1)
                    .addComponent(ButCancelar2)
                    .addComponent(ButCancelar3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaAlterarDadosProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPTelaAlterarDadosProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoProdutoActionPerformed

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        this.setVisible(false);
        new TelaMenuUsuario().setVisible(true);
    }//GEN-LAST:event_ButCancelarActionPerformed

    private void ButSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalvarActionPerformed
        int index = jTableAlterarDadosP.getSelectedRow();
        if(Integer.parseInt(txtRating.getText())<1 | Integer.parseInt(txtRating.getText())>100 & index>=0){
                    JOptionPane.showMessageDialog(null, "Digite um rating entre 1 e 100.", "Aviso!",
                    JOptionPane.ERROR_MESSAGE);
        }
        else if (index>=0){
            Produto prod_selected = TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index);
            prod_selected.setNome(txtNomeProduto.getText());
            prod_selected.setRating(Integer.parseInt(txtRating.getText()));
            prod_selected.setTipo(txtTipoProduto.getText());
            if(prod_selected instanceof Departamento){
                Departamento dep = (Departamento) prod_selected;
                dep.setCor(txtCor.getText());
                dep.setMarca(txtMarca.getText());
                dep.setUtilidade(txtUtilidade.getText());
            }else if(prod_selected instanceof Mercado){
                Mercado mark = (Mercado) prod_selected;
                mark.setCor(txtCor.getText());
                mark.setMarca(txtMarca.getText());
                mark.setUtilidade(txtUtilidade.getText());
                mark.setDatadevalidade(jFmtDataValidade.getText());
            }
            JOptionPane.showMessageDialog(null, "Informações atualizadas com sucesso.", "Aviso!",
                JOptionPane.INFORMATION_MESSAGE);
            // Limpar os campos.
            txtNomeProduto.setText("");
            txtRating.setText("");
            txtTipoProduto.setText("");
            txtCor.setText("");
            txtMarca.setText("");
            txtUtilidade.setText("");
            jFmtDataValidade.setText("");
            txtNomeProduto.requestFocus();
            carregarTabelaProd();
        }else{
            JOptionPane.showMessageDialog(null, "Informações atualizadas com sucesso.", "Aviso!",
                JOptionPane.INFORMATION_MESSAGE);
        }
                          
    }//GEN-LAST:event_ButSalvarActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatingActionPerformed

    private void txtCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtUtilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUtilidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUtilidadeActionPerformed

    private void jFmtDataValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataValidadeActionPerformed

    private void ButExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButExcluirActionPerformed
        if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum produto cadastrado.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);   
        }else{
            int index = jTableAlterarDadosP.getSelectedRow();
            if (index>=0){
                if(!Principal.department.isEmpty()){
                    if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index) instanceof Departamento){
                        Departamento dep = (Departamento) TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index);       
                        for(int i = 0;i<Principal.department.size();i++){
                            if(Principal.department.get(i).getNome().equals(dep.getNome()) & 
                                Principal.department.get(i).getUtilidade().equals(dep.getUtilidade())){
                                Principal.department.remove(i);
                            }
                        }
                    }
                    
                }
                if(!Principal.market.isEmpty()){
                    if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index) instanceof Mercado){
                        Mercado mark = (Mercado) TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(index);       
                        for(int i = 0;i<Principal.market.size();i++){
                            if(Principal.market.get(i).getNome().equals(mark.getNome()) & 
                                Principal.market.get(i).getUtilidade().equals(mark.getUtilidade())){
                                Principal.market.remove(i);
                            }
                        }
                    }
                    
                }
                
                TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.remove(index);
                carregarTabelaProd();
                txtNomeProduto.setText("");
                txtRating.setText("");
                txtTipoProduto.setText("");
                txtCor.setText("");
                txtMarca.setText("");
                txtUtilidade.setText("");
                jFmtDataValidade.setText("");
            }
        }
    }//GEN-LAST:event_ButExcluirActionPerformed

    private void ButAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButAlterarDadosActionPerformed
        produtoSelecionado();
    }//GEN-LAST:event_ButAlterarDadosActionPerformed

    private void ButCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelar1ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {

            Mercado e = new Mercado();
            ProdutoDAO dao = new ProdutoDAO();

            e.setIdProduto((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
           
            dao.delete(e);

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_ButCancelar1ActionPerformed

    private void ButCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelar2ActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeProduto.getText();   
        int rating = Integer.parseInt(txtRating.getText());
        String tipo = txtTipoProduto.getText();
        String cor = txtCor.getText();
        String marca = txtMarca.getText();
        String utilidade = txtUtilidade.getText();
        
        int idP = ((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        Departamento dep = new Departamento(nome, rating, tipo, cor, marca, utilidade, idP);
        ProdutoDAO dao = new ProdutoDAO();
        dao.update(dep);

        readJTable();
    }//GEN-LAST:event_ButCancelar2ActionPerformed

    private void ButCancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelar3ActionPerformed
        // TODO add your handling code here:
        String nome = txtNomeProduto.getText();   
        int rating = Integer.parseInt(txtRating.getText());
        String tipo = txtTipoProduto.getText();
        String cor = txtCor.getText();
        String marca = txtMarca.getText();
        String utilidade = txtUtilidade.getText();
        String datadevalidade = jFmtDataValidade.getText();
        
        int idP = ((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        Mercado mer = new Mercado(nome, rating, tipo, cor, marca, utilidade, datadevalidade, idP);
        ProdutoDAO dao = new ProdutoDAO();
        dao.update(mer);

        readJTable();
    }//GEN-LAST:event_ButCancelar3ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {

            txtNomeProduto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            txtRating.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            txtTipoProduto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            txtCor.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            txtMarca.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            txtUtilidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarDadosProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarDadosProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButAlterarDados;
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButCancelar1;
    private javax.swing.JButton ButCancelar2;
    private javax.swing.JButton ButCancelar3;
    private javax.swing.JButton ButExcluir;
    private javax.swing.JButton ButSalvar;
    private javax.swing.JFormattedTextField jFmtDataValidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPTelaAlterarDadosProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAlterarDadosP;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAlterarDadosP;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtTipoProduto;
    private javax.swing.JTextField txtUtilidade;
    // End of variables declaration//GEN-END:variables
}
