/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import codigoEscambot.Usuario;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author thiago
 */
public class TelaLogin extends javax.swing.JFrame {
    static int indexUser = -1;
    
            
    public TelaLogin() {
        initComponents();
    }
    public boolean CheckUsersLogPassword(String login, String senha){
        for(int i = 0;i<TelaCadastro.users.size();i++){
            if(TelaCadastro.users.get(i).getLogin().equals(login) & 
                    TelaCadastro.users.get(i).getSenha().equals(senha)){
                indexUser = i;
                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTelaLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        ButEntrar = new javax.swing.JButton();
        ButCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_transparent.png")).getImage());
        setResizable(false);

        jPTelaLogin.setBackground(new java.awt.Color(106, 97, 87));
        jPTelaLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela de Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(10, 3, 3))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(20, 10, 10));
        jLabel1.setText("Login");

        txtLogin.setToolTipText("Digite seu login");
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(20, 10, 10));
        jLabel2.setText("Senha");

        txtSenha.setToolTipText("Digite sua senha");
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        ButEntrar.setBackground(new java.awt.Color(234, 234, 27));
        ButEntrar.setMnemonic('e');
        ButEntrar.setText("Entrar");
        ButEntrar.setToolTipText("Clique para entrar");
        ButEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButEntrarActionPerformed(evt);
            }
        });

        ButCancelar.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar.setMnemonic('c');
        ButCancelar.setText("Cancelar");
        ButCancelar.setToolTipText("Clique para cancelar o login");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTelaLoginLayout = new javax.swing.GroupLayout(jPTelaLogin);
        jPTelaLogin.setLayout(jPTelaLoginLayout);
        jPTelaLoginLayout.setHorizontalGroup(
            jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButCancelar)
                .addGap(18, 18, 18)
                .addComponent(ButEntrar)
                .addContainerGap())
            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPTelaLoginLayout.setVerticalGroup(
            jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButEntrar)
                    .addComponent(ButCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        this.setVisible(false);
        new Principal().setVisible(true);
    }//GEN-LAST:event_ButCancelarActionPerformed

    private void ButEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButEntrarActionPerformed
        
       
        //System.out.println(user.getUsuarios().size());
        //System.out.println(user.getUsuarios().isEmpty());
        
        if(txtLogin.getText().equals("") | txtSenha.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de clicar em Entrar.", "Aviso!",
                JOptionPane.ERROR_MESSAGE); 
            
            txtLogin.setText("");
            txtSenha.setText("");
                    
            txtLogin.requestFocus();
           
        } else if(txtLogin.getText().equals("dev") && txtSenha.getText().equals("1234")){
            String data = "99/99/9999";
            Usuario dev = new Usuario("Lagoinha", "190", "devi", data, "000.000.000-00", "1234", "dev", 10001);
            if(TelaCadastro.users == null){
                TelaCadastro.users = new ArrayList();
            }
            TelaCadastro.users.add(dev);
            indexUser = 0;
            this.setVisible(false);
            new TelaMenuUsuario().setVisible(true);
        
           
        }
        else if(TelaCadastro.users == null){
            JOptionPane.showMessageDialog(null, "Por favor cadastre um usuário.", "Aviso!",
                    JOptionPane.ERROR_MESSAGE);
        }else{
            if(CheckUsersLogPassword(txtLogin.getText(), txtSenha.getText())){
                this.setVisible(false);
                new TelaMenuUsuario().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Senha ou usuário incorretos.", "Aviso!",
                    JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_ButEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPTelaLogin;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
