/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import codigoEscambot.Empregado;
import codigoEscambot.Escambo;
import codigoEscambot.Mercado;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dao.EmpregadoDAO;
import model.dao.EscamboDAO;
import model.dao.ProdutoDAO;
import telas.TelaMenuUsuario;

/**
 *
 * @author thiago
 */
public class TelaEscambo extends javax.swing.JFrame {
    public int cont = 0;
    public int drating = 0;
    public int r1 = 0;
    public int r2 = 0;
    public int trocas= 0;
    

    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        ProdutoDAO pdao = new ProdutoDAO();

        for (Mercado p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getIdProduto(),
                p.getNome(),
                p.getRating(),
                p.getTipo(),
                p.getCor(),
                p.getMarca(),
                p.getUtilidade(),
            });

        }

    }
    
    
    public void carregarTabelaProdutoU(){
        if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.size() != 0){
            DefaultTableModel modelo = new DefaultTableModel(new Object [] {"Nome","Rating"},0);
       
            for(int i=0;i<TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.size();i++){
                Object linha[] = new Object[]{TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(i).getNome(), 
                        TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(i).getRating()};
                modelo.addRow(linha);
                }
            jTableListaSP.setModel(modelo);
        
        }
    }
    
    public void carregarTabelaProdutoT(){
            DefaultTableModel model0 = new DefaultTableModel(new Object [] {"Nome","Rating"},0);
            if(Principal.department != null){
                for(int i = 0; i<Principal.department.size(); i++){
                    Object line0[] = new Object[]{Principal.department.get(i).getNome(),
                                                  Principal.department.get(i).getRating()};
                    model0.addRow(line0);
            }
        }
            if(Principal.market != null){
                for(int i = 0; i<Principal.market.size(); i++){
                    Object line0[] = new Object[]{Principal.market.get(i).getNome(),
                                                  Principal.market.get(i).getRating()};
                    model0.addRow(line0);
                }
            }
            jTableListaP.setModel(model0);
        }

    /**
     * Creates new form telaLogin
     */
    public TelaEscambo() {
        initComponents();
        carregarTabelaProdutoT();
        
        if(!TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.isEmpty())
            carregarTabelaProdutoU();
        
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneAlterarDadosP1 = new javax.swing.JScrollPane();
        jTableAlterarDadosP2 = new javax.swing.JTable();
        jPTelaEscambo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBarraPesquisaP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPaneProdutoP = new javax.swing.JScrollPane();
        jTableListaP = new javax.swing.JTable();
        jButEscambot = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBarraPesquisaSProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPaneSeuProduto = new javax.swing.JScrollPane();
        jTableListaSP = new javax.swing.JTable();
        ButCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTableAlterarDadosP2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome do produto", "Rating"
            }
        ));
        jScrollPaneAlterarDadosP1.setViewportView(jTableAlterarDadosP2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escambot");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_transparent.png")).getImage());
        setResizable(false);

        jPTelaEscambo.setBackground(new java.awt.Color(106, 97, 87));
        jPTelaEscambo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela escambo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(10, 3, 3))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(20, 10, 10));
        jLabel1.setText("Nome do seu produto para troca");

        txtBarraPesquisaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraPesquisaPActionPerformed(evt);
            }
        });
        txtBarraPesquisaP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarraPesquisaPKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(20, 10, 10));
        jLabel3.setText("Lista dos produtos disponíveis para troca");

        jScrollPaneProdutoP.setBackground(new java.awt.Color(92, 92, 79));
        jScrollPaneProdutoP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneProdutoP.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableListaP.setBackground(new java.awt.Color(92, 92, 79));
        jTableListaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome do produto", "Rating"
            }
        ));
        jTableListaP.setGridColor(new java.awt.Color(60, 60, 60));
        jTableListaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaPMouseClicked(evt);
            }
        });
        jTableListaP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableListaPKeyReleased(evt);
            }
        });
        jScrollPaneProdutoP.setViewportView(jTableListaP);

        jButEscambot.setBackground(new java.awt.Color(234, 234, 27));
        jButEscambot.setMnemonic('e');
        jButEscambot.setText("Escambot");
        jButEscambot.setToolTipText("Clique para efetuar um Escambo");
        jButEscambot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEscambotActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(20, 10, 10));
        jLabel4.setText("Nome do produto para troca");

        txtBarraPesquisaSProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraPesquisaSProdutoActionPerformed(evt);
            }
        });
        txtBarraPesquisaSProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBarraPesquisaSProdutoKeyReleased(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(20, 10, 10));
        jLabel6.setText("Lista dos seus produtos disponíveis para troca");

        jScrollPaneSeuProduto.setBackground(new java.awt.Color(92, 92, 79));
        jScrollPaneSeuProduto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPaneSeuProduto.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTableListaSP.setBackground(new java.awt.Color(92, 92, 79));
        jTableListaSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome do produto", "Rating"
            }
        ));
        jTableListaSP.setGridColor(new java.awt.Color(60, 60, 60));
        jTableListaSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaSPMouseClicked(evt);
            }
        });
        jScrollPaneSeuProduto.setViewportView(jTableListaSP);

        ButCancelar.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar.setMnemonic('c');
        ButCancelar.setText("Cancelar");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Produto", "Nome do Produto", "Rating", "Tipo do produto", "Cor ", "Marca", "Utilidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPTelaEscamboLayout = new javax.swing.GroupLayout(jPTelaEscambo);
        jPTelaEscambo.setLayout(jPTelaEscamboLayout);
        jPTelaEscamboLayout.setHorizontalGroup(
            jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                        .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButCancelar)
                            .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                                .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                                                .addGap(365, 365, 365)
                                                .addComponent(txtBarraPesquisaSProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                                                .addGap(444, 444, 444)
                                                .addComponent(jButEscambot, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaEscamboLayout.createSequentialGroup()
                                                .addGap(365, 365, 365)
                                                .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtBarraPesquisaP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaEscamboLayout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(30, 30, 30))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaEscamboLayout.createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addGap(39, 39, 39))))))
                                    .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                                        .addComponent(jScrollPaneProdutoP, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(331, 331, 331)))
                                .addGap(18, 18, 18)
                                .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPaneSeuProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPTelaEscamboLayout.setVerticalGroup(
            jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaEscamboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneProdutoP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPTelaEscamboLayout.createSequentialGroup()
                        .addGap(0, 113, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBarraPesquisaSProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButEscambot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBarraPesquisaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneSeuProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButCancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaEscambo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaEscambo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        this.setVisible(false);
        new TelaMenuUsuario().setVisible(true);
    }//GEN-LAST:event_ButCancelarActionPerformed

    private void txtBarraPesquisaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraPesquisaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarraPesquisaPActionPerformed

    private void txtBarraPesquisaSProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraPesquisaSProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarraPesquisaSProdutoActionPerformed

    private void jButEscambotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEscambotActionPerformed
//        
//        for(int i = 0;i<TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.size();i++){
//            if(TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.get(i).getNome().equals(txtBarraPesquisaSProduto.getText())){
//                TelaCadastro.users.get(TelaLogin.indexUser).produtos_user.remove(i);
//                
//                for(int j = 0;j<TelaCadastro.users.size();j++){
//                    for(int t = 0;t<TelaCadastro.users.get(j).produtos_user.size();t++){
//                        if (TelaCadastro.users.get(j).produtos_user.get(t).getNome().equals(txtBarraPesquisaP.getText())) {
//                            TelaCadastro.users.get(j).produtos_user.remove(t);                            
//                            break;
//                        }
//                    }      
//                }
//                
//                break;
//            }
//        }
//        for(int i = 0;i<Principal.department.size();i++){
//            if(Principal.department.get(i).getNome().equals(txtBarraPesquisaP.getText())){
//                Principal.department.remove(i);
//                break;
//            } 
//        }
//        for(int i = 0;i<Principal.department.size();i++){
//            if(Principal.department.get(i).getNome().equals(txtBarraPesquisaSProduto.getText())){
//                Principal.department.remove(i);
//                break;
//            } 
//        }
//        
//        for(int i = 0;i<Principal.market.size();i++){
//            if(Principal.market.get(i).getNome().equals(txtBarraPesquisaP.getText())){
//                Principal.market.remove(i);
//                break;
//            }
//        }
//        
//        for(int i = 0;i<Principal.market.size();i++){
//            if(Principal.market.get(i).getNome().equals(txtBarraPesquisaSProduto.getText())){
//                Principal.market.remove(i);
//                break;
//            }
//        }
             
//        JOptionPane.showMessageDialog(null, "Escambot realizado. O produto de nome: " + txtBarraPesquisaP.getText()
//                + " foi enviado ao endereço cadastrado: " + TelaCadastro.users.get(TelaLogin.indexUser).getCidade()
//                + ".", "Aviso!",
//                JOptionPane.INFORMATION_MESSAGE);
            Random rand = new Random();
            int x = rand.nextInt(10000);
            int y = rand.nextInt(10000);
            String data = "29/04/2022";
            EscamboDAO dao = new EscamboDAO();
            int t = jTable1.getRowCount();
            int r = r1-r2;
            trocas++;
            int a = Integer.parseInt(txtBarraPesquisaSProduto.getText());
            int b = Integer.parseInt(txtBarraPesquisaP.getText());
            Escambo esc = new Escambo(x, t, r, data, 0, Integer.parseInt(txtBarraPesquisaSProduto.getText()), 0, y, trocas, x);
            dao.Escambo(esc, a, b);
            readJTable();
            JOptionPane.showMessageDialog(null, "Escambot realizado."
                + ".", "Aviso!",
                JOptionPane.INFORMATION_MESSAGE);
        
        txtBarraPesquisaSProduto.setText("");
        txtBarraPesquisaP.setText("");
        
//        this.setVisible(false);
//        new TelaMenuUsuario().setVisible(true);
        
    }//GEN-LAST:event_jButEscambotActionPerformed

    private void jTableListaSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaSPMouseClicked
        //produtoSelecionadoLSP();
    }//GEN-LAST:event_jTableListaSPMouseClicked

    private void jTableListaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaPMouseClicked
        //produtoSelecionadoLP();
    }//GEN-LAST:event_jTableListaPMouseClicked

    private void txtBarraPesquisaSProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarraPesquisaSProdutoKeyReleased
        DefaultTableModel pesquisa = (DefaultTableModel)jTableListaSP.getModel();
        String nom = txtBarraPesquisaSProduto.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(pesquisa);
        jTableListaSP.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(nom));
    }//GEN-LAST:event_txtBarraPesquisaSProdutoKeyReleased

    private void jTableListaPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableListaPKeyReleased
        
    }//GEN-LAST:event_jTableListaPKeyReleased

    private void txtBarraPesquisaPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBarraPesquisaPKeyReleased
        DefaultTableModel pesquisa = (DefaultTableModel)jTableListaP.getModel();
        String nom = txtBarraPesquisaP.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(pesquisa);
        jTableListaP.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(nom));
    }//GEN-LAST:event_txtBarraPesquisaPKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        
         if (jTable1.getSelectedRow() != -1) {
             
             if(cont % 2 == 0){
                txtBarraPesquisaSProduto.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                int r1 = ((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                cont++;
             }
             
             else{
                txtBarraPesquisaP.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
                int r2 = ((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                cont++;
             }
            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscambo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscambo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscambo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscambo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscambo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton jButEscambot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPTelaEscambo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAlterarDadosP1;
    private javax.swing.JScrollPane jScrollPaneProdutoP;
    private javax.swing.JScrollPane jScrollPaneSeuProduto;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableAlterarDadosP2;
    private javax.swing.JTable jTableListaP;
    private javax.swing.JTable jTableListaSP;
    private javax.swing.JTextField txtBarraPesquisaP;
    private javax.swing.JTextField txtBarraPesquisaSProduto;
    // End of variables declaration//GEN-END:variables
}
