/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author thiago
 */
public class TelaMenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenuUsuario
     */
    public TelaMenuUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jPMenuUsuario = new javax.swing.JPanel();
        jButAlterarDados = new javax.swing.JButton();
        jButPesquisarProduto = new javax.swing.JButton();
        jButAlterarDadosProduto = new javax.swing.JButton();
        jButAdicionarProdutos = new javax.swing.JButton();
        jButEscambo = new javax.swing.JButton();
        jButSair = new javax.swing.JButton();
        jButSair1 = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do Usuário");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_transparent.png")).getImage());
        setResizable(false);

        jPMenuUsuario.setBackground(new java.awt.Color(106, 97, 87));
        jPMenuUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu do Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(10, 3, 3))); // NOI18N

        jButAlterarDados.setBackground(new java.awt.Color(234, 234, 27));
        jButAlterarDados.setMnemonic('a');
        jButAlterarDados.setText("Alterar seus dados");
        jButAlterarDados.setToolTipText("Clique para alterar seus dados");
        jButAlterarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlterarDadosActionPerformed(evt);
            }
        });

        jButPesquisarProduto.setBackground(new java.awt.Color(92, 92, 79));
        jButPesquisarProduto.setMnemonic('p');
        jButPesquisarProduto.setText("Pesquisar produtos");
        jButPesquisarProduto.setToolTipText("Clique para pesquisar produtos");
        jButPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPesquisarProdutoActionPerformed(evt);
            }
        });

        jButAlterarDadosProduto.setBackground(new java.awt.Color(234, 234, 27));
        jButAlterarDadosProduto.setMnemonic('d');
        jButAlterarDadosProduto.setText("Alterar dados do produto");
        jButAlterarDadosProduto.setToolTipText("Clique para alterar os dados do produto");
        jButAlterarDadosProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAlterarDadosProdutoActionPerformed(evt);
            }
        });

        jButAdicionarProdutos.setBackground(new java.awt.Color(92, 92, 79));
        jButAdicionarProdutos.setMnemonic('a');
        jButAdicionarProdutos.setText("Adicionar produtos");
        jButAdicionarProdutos.setToolTipText("Clique para adicionar produtos");
        jButAdicionarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAdicionarProdutosActionPerformed(evt);
            }
        });

        jButEscambo.setBackground(new java.awt.Color(234, 234, 27));
        jButEscambo.setMnemonic('e');
        jButEscambo.setText("Escambo");
        jButEscambo.setToolTipText("Clique para efetuar um Escambo");
        jButEscambo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEscamboActionPerformed(evt);
            }
        });

        jButSair.setBackground(new java.awt.Color(92, 92, 79));
        jButSair.setMnemonic('s');
        jButSair.setText("Sair");
        jButSair.setToolTipText("Clique para sair ");
        jButSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSairActionPerformed(evt);
            }
        });

        jButSair1.setBackground(new java.awt.Color(234, 234, 27));
        jButSair1.setMnemonic('s');
        jButSair1.setText("Cadastro Funcionário");
        jButSair1.setToolTipText("Clique para sair ");
        jButSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSair1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMenuUsuarioLayout = new javax.swing.GroupLayout(jPMenuUsuario);
        jPMenuUsuario.setLayout(jPMenuUsuarioLayout);
        jPMenuUsuarioLayout.setHorizontalGroup(
            jPMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuUsuarioLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButSair1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButAlterarDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButAdicionarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButAlterarDadosProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jButPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButEscambo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPMenuUsuarioLayout.setVerticalGroup(
            jPMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuUsuarioLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAlterarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButEscambo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButAlterarDadosProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButSair, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenuUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPMenuUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButAlterarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlterarDadosActionPerformed
        this.setVisible(false);
        new TelaAlterarDadosUsuario().setVisible(true);
    }//GEN-LAST:event_jButAlterarDadosActionPerformed

    private void jButPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPesquisarProdutoActionPerformed
        this.setVisible(false);
        new TelaPesquisarProduto().setVisible(true);
    }//GEN-LAST:event_jButPesquisarProdutoActionPerformed

    private void jButAlterarDadosProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAlterarDadosProdutoActionPerformed
        this.setVisible(false);
        new TelaAlterarDadosProduto().setVisible(true);
    }//GEN-LAST:event_jButAlterarDadosProdutoActionPerformed

    private void jButAdicionarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAdicionarProdutosActionPerformed
        this.setVisible(false);
        new TelaAdicionaProduto().setVisible(true);
    }//GEN-LAST:event_jButAdicionarProdutosActionPerformed

    private void jButEscamboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEscamboActionPerformed
        this.setVisible(false);
        new TelaEscambo().setVisible(true);
    }//GEN-LAST:event_jButEscamboActionPerformed

    private void jButSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSairActionPerformed
        this.setVisible(false);
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jButSairActionPerformed

    private void jButSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSair1ActionPerformed
        this.setVisible(false);
        new TelaCadastroEmpregado().setVisible(true);
    }//GEN-LAST:event_jButSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenuUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenuUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAdicionarProdutos;
    private javax.swing.JButton jButAlterarDados;
    private javax.swing.JButton jButAlterarDadosProduto;
    private javax.swing.JButton jButEscambo;
    private javax.swing.JButton jButPesquisarProduto;
    private javax.swing.JButton jButSair;
    private javax.swing.JButton jButSair1;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
