/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import codigoEscambot.Empregado;
import codigoEscambot.Usuario;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import java.util.ArrayList;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.dao.EmpregadoDAO;
import model.dao.UsuarioDAO;
import util.ManipularImagem;

/**
 *
 * @author thiago
 */
public class TelaCadastroEmpregado extends javax.swing.JFrame {

    static ArrayList<Usuario> users;
     BufferedImage imagem;

    
    public TelaCadastroEmpregado() {
        initComponents();
        if(users == null){
            users = new ArrayList();
        }
        readJTable();
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        EmpregadoDAO edao = new EmpregadoDAO();

        for (Empregado e : edao.read()) {

            modelo.addRow(new Object[]{
                e.getID(),
                e.getSenha(),
                e.getLogin(),
                e.getNome(),
                e.getData(),
                e.getCpf(),
                e.getCidade(),
                e.getTelefone(),
                e.getE_mail(),
                e.getCargo(),
                e.getIdPrivilegios()
            });

        }

    }
    
    public void readJTableForNome(String nome) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        EmpregadoDAO edao = new EmpregadoDAO();

        for (Empregado e : edao.readNome(nome)) {

            modelo.addRow(new Object[]{
                e.getID(),
                e.getSenha(),
                e.getLogin(),
                e.getNome(),
                e.getData(),
                e.getCpf(),
                e.getCidade(),
                e.getTelefone(),
                e.getE_mail(),
                e.getCargo(),
                e.getIdPrivilegios()
            });

        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTelaLogin = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jCBEstados = new javax.swing.JComboBox<>();
        jLabelTelefone = new javax.swing.JLabel();
        txtNome3 = new javax.swing.JTextField();
        jLabelLogin = new javax.swing.JLabel();
        txtLoginC = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPwdSenhaC = new javax.swing.JPasswordField();
        ButSalvar = new javax.swing.JButton();
        ButCancelar = new javax.swing.JButton();
        lblImagem = new javax.swing.JLabel();
        btnImagem = new javax.swing.JButton();
        txtLoginC1 = new javax.swing.JTextField();
        jLabelSenha1 = new javax.swing.JLabel();
        jLabelSenha2 = new javax.swing.JLabel();
        txtLoginC2 = new javax.swing.JTextField();
        jLabelSenha3 = new javax.swing.JLabel();
        txtLoginC3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ButCancelar1 = new javax.swing.JButton();
        ButCancelar2 = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        Busca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_transparent.png")).getImage());
        setResizable(false);

        jPTelaLogin.setBackground(new java.awt.Color(106, 97, 87));
        jPTelaLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela de Cadastro Empregados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(10, 3, 3))); // NOI18N

        jLabelNome.setForeground(new java.awt.Color(20, 10, 10));
        jLabelNome.setText("Nome");

        txtNome.setToolTipText("Digite seu nome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabelDataNascimento.setForeground(new java.awt.Color(20, 10, 10));
        jLabelDataNascimento.setText("Data de nascimento");

        txtNome1.setToolTipText("Digite seu nome");
        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });

        jLabelCPF.setForeground(new java.awt.Color(20, 10, 10));
        jLabelCPF.setText("CPF");

        txtNome2.setToolTipText("Digite seu nome");
        txtNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome2ActionPerformed(evt);
            }
        });

        jLabelCidade.setForeground(new java.awt.Color(20, 10, 10));
        jLabelCidade.setText("Cidade");

        txtCidade.setToolTipText("Digite sua cidade");
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        jLabelEstado.setForeground(new java.awt.Color(20, 10, 10));
        jLabelEstado.setText("Estado");

        jCBEstados.setBackground(new java.awt.Color(92, 92, 79));
        jCBEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu estado", "Acre - AC ", "Alagoas - AL", "Amapá - AP ", "Amazonas - AM", "Bahia - BA", "Ceará - CE ", "Distrito Federal - DF", "Espírito Santo - ES", "Goiás - GO ", "Maranhão - MA ", "Mato Grosso - MT", "Mato Grosso do Sul - MS ", "Minas Gerais - MG", "Pará - PA", "Paraíba - PB ", "Paraná - PR ", "Pernambuco - PE ", "Piauí - PI", "Roraima - RR ", "Rondônia - RO ", "Rio de Janeiro - RJ ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS ", "Santa Catarina - SC ", "São Paulo - SP ", "Sergipe - SE ", "Tocantins - TO" }));
        jCBEstados.setToolTipText("Selecione seu estado");
        jCBEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadosActionPerformed(evt);
            }
        });

        jLabelTelefone.setForeground(new java.awt.Color(20, 10, 10));
        jLabelTelefone.setText("Telefone");

        txtNome3.setToolTipText("Digite seu nome");
        txtNome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome3ActionPerformed(evt);
            }
        });

        jLabelLogin.setForeground(new java.awt.Color(20, 10, 10));
        jLabelLogin.setText("Login");

        txtLoginC.setToolTipText("Digite um login");
        txtLoginC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginCActionPerformed(evt);
            }
        });

        jLabelSenha.setForeground(new java.awt.Color(20, 10, 10));
        jLabelSenha.setText("Senha");

        jPwdSenhaC.setToolTipText("Digite uma senha");
        jPwdSenhaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwdSenhaCActionPerformed(evt);
            }
        });

        ButSalvar.setBackground(new java.awt.Color(234, 234, 27));
        ButSalvar.setMnemonic('s');
        ButSalvar.setText("Salvar");
        ButSalvar.setToolTipText("Clique para salvar os dados");
        ButSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalvarActionPerformed(evt);
            }
        });

        ButCancelar.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar.setMnemonic('c');
        ButCancelar.setText("Cancelar");
        ButCancelar.setToolTipText("Clique para cancelar o cadastro");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        btnImagem.setText("Selecionar Imagem");
        btnImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagemActionPerformed(evt);
            }
        });

        txtLoginC1.setToolTipText("Digite um login");
        txtLoginC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginC1ActionPerformed(evt);
            }
        });

        jLabelSenha1.setForeground(new java.awt.Color(20, 10, 10));
        jLabelSenha1.setText("Cargo");

        jLabelSenha2.setForeground(new java.awt.Color(20, 10, 10));
        jLabelSenha2.setText("E-mail");

        txtLoginC2.setToolTipText("Digite um login");
        txtLoginC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginC2ActionPerformed(evt);
            }
        });

        jLabelSenha3.setForeground(new java.awt.Color(20, 10, 10));
        jLabelSenha3.setText("Privilégios(0 ou 1)");

        txtLoginC3.setToolTipText("Digite um login");
        txtLoginC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginC3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Senha", "Login", "Nome", "Data De Nascimento", "CPF", "Cidade", "Telefone", "E-mail", "Cargo", "IDPrivilégios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ButCancelar1.setBackground(new java.awt.Color(234, 234, 27));
        ButCancelar1.setMnemonic('c');
        ButCancelar1.setText("Deletar");
        ButCancelar1.setToolTipText("Clique para cancelar o cadastro");
        ButCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelar1ActionPerformed(evt);
            }
        });

        ButCancelar2.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar2.setMnemonic('c');
        ButCancelar2.setText("Atualizar");
        ButCancelar2.setToolTipText("Clique para cancelar o cadastro");
        ButCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelar2ActionPerformed(evt);
            }
        });

        Busca.setBackground(new java.awt.Color(234, 234, 27));
        Busca.setMnemonic('c');
        Busca.setText("Busca");
        Busca.setToolTipText("Clique para cancelar a alteração dos dados");
        Busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTelaLoginLayout = new javax.swing.GroupLayout(jPTelaLogin);
        jPTelaLogin.setLayout(jPTelaLoginLayout);
        jPTelaLoginLayout.setHorizontalGroup(
            jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaLoginLayout.createSequentialGroup()
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPTelaLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPTelaLoginLayout.createSequentialGroup()
                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLoginC3)
                                    .addComponent(jLabelSenha1)
                                    .addComponent(jLabelSenha3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(90, 90, 90)
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Busca)
                                .addGap(18, 18, 18)
                                .addComponent(ButCancelar2)
                                .addGap(18, 18, 18)
                                .addComponent(ButCancelar1)
                                .addGap(18, 18, 18)
                                .addComponent(ButCancelar)))
                        .addGap(12, 12, 12)
                        .addComponent(ButSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPTelaLoginLayout.createSequentialGroup()
                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoginC1)
                            .addComponent(jPwdSenhaC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLoginC2)
                            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDataNascimento)
                                    .addComponent(jLabelSenha)
                                    .addComponent(jLabelCPF)
                                    .addGroup(jPTelaLoginLayout.createSequentialGroup()
                                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCidade)
                                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(5, 5, 5)
                                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCBEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelEstado)))
                                    .addComponent(txtLoginC, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTelefone)
                                    .addComponent(jLabelLogin)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSenha2)
                                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addContainerGap())
        );
        jPTelaLoginLayout.setVerticalGroup(
            jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(btnImagem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTelaLoginLayout.createSequentialGroup()
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDataNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoginC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPwdSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSenha2)
                        .addGap(5, 5, 5)
                        .addComponent(txtLoginC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPTelaLoginLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSenha3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCancelar)
                    .addComponent(ButSalvar)
                    .addComponent(txtLoginC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButCancelar1)
                    .addComponent(ButCancelar2)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Busca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPTelaLogin.getAccessibleContext().setAccessibleName("Tela de Cadastro do Empregado");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        new TelaMenuUsuario().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButCancelarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void ButSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalvarActionPerformed
        int index = jCBEstados.getSelectedIndex();
        int jaexiste = 0;
        if(index == 0){
            JOptionPane.showMessageDialog(null, "Selecione um Estado.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);         
        }
        else if(txtNome.getText().equals("") | txtNome2.getText().equals("   .   .   -  ") | txtNome3.getText().equals("(  )9    -    ") |
                txtCidade.getText().equals("") | txtLoginC.getText().equals("") |
                jPwdSenhaC.getText().equals("") | txtNome1.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de clicar em Salvar.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);         
        }
        else{
            String nome = txtNome.getText();
            String data = txtNome1.getText();
            String cpf = txtNome2.getText();
            String cidade = txtCidade.getText();
            String estado = jCBEstados.getSelectedItem().toString();
            String telefone = txtNome3.getText();
            String senha = jPwdSenhaC.getText();
            String login = txtLoginC.getText();
            String e_mail = txtLoginC2.getText();
            String cargo = txtLoginC1.getText();
            String Privilegios = txtLoginC3.getText();
            
            for(int j = 0;j<users.size();j++){
                if(users.get(j).getLogin().equals(login)){
                    JOptionPane.showMessageDialog(null, "Já existe um usuário com esse login.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);
                    jaexiste++;
                    break;
                }
            }
            if(jaexiste == 0){
                Random rand = new Random();
                int x = rand.nextInt(10000);
                Empregado epre = new Empregado(x, telefone, e_mail, cargo, nome, data, cpf, senha, login, Privilegios, cidade);
                EmpregadoDAO dao = new EmpregadoDAO();
                dao.create(epre);
                JOptionPane.showMessageDialog(null, "Empregado criado com sucesso.", "Aviso!",
                    JOptionPane.INFORMATION_MESSAGE);
                // Limpar os campos.
                txtNome.setText("");
                txtNome1.setText("");
                txtNome2.setText("");
                txtCidade.setText("");
                txtNome3.setText("");
                txtLoginC.setText("");
                jPwdSenhaC.setText("");
                txtLoginC2.setText("");
                txtLoginC1.setText("");

                txtNome.requestFocus();
            }
        }
        
        readJTable();
//        try {
//            // TODO add your handling code here:
//            String caminho = getClass().getResource("../imagens/").toString().substring(5);
//            File outputfile = new File(caminho+"image.jpg");
//            ImageIO.write(imagem, "jpg", outputfile);
//            JOptionPane.showMessageDialog(rootPane, "Imagem enviada com sucesso");
//        } catch (IOException ex) {
//        }
        
    }//GEN-LAST:event_ButSalvarActionPerformed

    private void txtLoginCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginCActionPerformed

    private void jCBEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadosActionPerformed
        
    }//GEN-LAST:event_jCBEstadosActionPerformed

    private void btnImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();

            
                imagem = ManipularImagem.setImagemDimensao(arquivo.getAbsolutePath(), 480, 480);

                lblImagem.setIcon(new ImageIcon(imagem));

            

        }
    }//GEN-LAST:event_btnImagemActionPerformed

    private void txtLoginC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginC1ActionPerformed

    private void txtLoginC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginC2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginC2ActionPerformed

    private void txtLoginC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginC3ActionPerformed

    private void ButCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelar1ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {

            Empregado e = new Empregado();
            EmpregadoDAO dao = new EmpregadoDAO();

            e.setID((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            e.setNome((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3));
            
            dao.delete(e);

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_ButCancelar1ActionPerformed

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void txtNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome2ActionPerformed

    private void txtNome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome3ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() != -1) {

            txtNome.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
            txtNome1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
            txtNome2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
            txtCidade.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6).toString());
            txtNome3.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString());
            txtLoginC.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jPwdSenhaC.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            txtLoginC2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString());
            txtLoginC1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString());
            
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jPwdSenhaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwdSenhaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwdSenhaCActionPerformed

    private void ButCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelar2ActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText();
        String data = txtNome1.getText();
        String cpf = txtNome2.getText();
        String cidade = txtCidade.getText();
        String estado = jCBEstados.getSelectedItem().toString();
        cidade = cidade + " " + estado;
        String telefone = txtNome3.getText();
        String senha = jPwdSenhaC.getText();
        String login = txtLoginC.getText();
        String e_mail = txtLoginC2.getText();
        String cargo = txtLoginC1.getText();
        String Privilegios = txtLoginC3.getText();
            
        int id = ((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        int idP = ((int)jTable1.getValueAt(jTable1.getSelectedRow(), 10));
        Empregado epre = new Empregado(id, telefone, e_mail, cargo, nome, data, cpf, senha, login, Privilegios, cidade, idP);
        EmpregadoDAO dao = new EmpregadoDAO();
        dao.update(epre);
        
        readJTable();
    }//GEN-LAST:event_ButCancelar2ActionPerformed

    private void BuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaActionPerformed
        // TODO add your handling code here:
        readJTableForNome(txtBusca.getText());
    }//GEN-LAST:event_BuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEmpregado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Busca;
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButCancelar1;
    private javax.swing.JButton ButCancelar2;
    private javax.swing.JButton ButSalvar;
    private javax.swing.JButton btnImagem;
    private javax.swing.JComboBox<String> jCBEstados;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSenha1;
    private javax.swing.JLabel jLabelSenha2;
    private javax.swing.JLabel jLabelSenha3;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPTelaLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPwdSenhaC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtLoginC;
    private javax.swing.JTextField txtLoginC1;
    private javax.swing.JTextField txtLoginC2;
    private javax.swing.JTextField txtLoginC3;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNome2;
    private javax.swing.JTextField txtNome3;
    // End of variables declaration//GEN-END:variables
}
