/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import codigoEscambot.Usuario;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Random;
import model.dao.UsuarioDAO;

/**
 *
 * @author thiago
 */
public class TelaCadastro extends javax.swing.JFrame {

    static ArrayList<Usuario> users;

    
    public TelaCadastro() {
        initComponents();
        if(users == null){
            users = new ArrayList();
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTelaLogin = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jFmtDataNascimento = new javax.swing.JFormattedTextField();
        jLabelCPF = new javax.swing.JLabel();
        jFmtCPF = new javax.swing.JFormattedTextField();
        jLabelCidade = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jCBEstados = new javax.swing.JComboBox<>();
        jLabelTelefone = new javax.swing.JLabel();
        jFmtTelefone = new javax.swing.JFormattedTextField();
        jLabelLogin = new javax.swing.JLabel();
        txtLoginC = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPwdSenhaC = new javax.swing.JPasswordField();
        ButSalvar = new javax.swing.JButton();
        ButCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_transparent.png")).getImage());
        setResizable(false);

        jPTelaLogin.setBackground(new java.awt.Color(106, 97, 87));
        jPTelaLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela de Cadastro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(10, 3, 3))); // NOI18N

        jLabelNome.setForeground(new java.awt.Color(20, 10, 10));
        jLabelNome.setText("Nome");

        txtNome.setToolTipText("Digite seu nome");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabelDataNascimento.setForeground(new java.awt.Color(20, 10, 10));
        jLabelDataNascimento.setText("Data de nascimento");

        try {
            jFmtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtDataNascimento.setToolTipText("Digite sua data de nascimento");
        jFmtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNascimentoActionPerformed(evt);
            }
        });

        jLabelCPF.setForeground(new java.awt.Color(20, 10, 10));
        jLabelCPF.setText("CPF");

        try {
            jFmtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtCPF.setToolTipText("Digite seu CPF");

        jLabelCidade.setForeground(new java.awt.Color(20, 10, 10));
        jLabelCidade.setText("Cidade");

        txtCidade.setToolTipText("Digite sua cidade");
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });

        jLabelEstado.setForeground(new java.awt.Color(20, 10, 10));
        jLabelEstado.setText("Estado");

        jCBEstados.setBackground(new java.awt.Color(92, 92, 79));
        jCBEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu estado", "Acre - AC ", "Alagoas - AL", "Amapá - AP ", "Amazonas - AM", "Bahia - BA", "Ceará - CE ", "Distrito Federal - DF", "Espírito Santo - ES", "Goiás - GO ", "Maranhão - MA ", "Mato Grosso - MT", "Mato Grosso do Sul - MS ", "Minas Gerais - MG", "Pará - PA", "Paraíba - PB ", "Paraná - PR ", "Pernambuco - PE ", "Piauí - PI", "Roraima - RR ", "Rondônia - RO ", "Rio de Janeiro - RJ ", "Rio Grande do Norte - RN", "Rio Grande do Sul - RS ", "Santa Catarina - SC ", "São Paulo - SP ", "Sergipe - SE ", "Tocantins - TO" }));
        jCBEstados.setToolTipText("Selecione seu estado");
        jCBEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadosActionPerformed(evt);
            }
        });

        jLabelTelefone.setForeground(new java.awt.Color(20, 10, 10));
        jLabelTelefone.setText("Telefone");

        try {
            jFmtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtTelefone.setToolTipText("Digite seu telefone");

        jLabelLogin.setForeground(new java.awt.Color(20, 10, 10));
        jLabelLogin.setText("Login");

        txtLoginC.setToolTipText("Digite um login");
        txtLoginC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginCActionPerformed(evt);
            }
        });

        jLabelSenha.setForeground(new java.awt.Color(20, 10, 10));
        jLabelSenha.setText("Senha");

        jPwdSenhaC.setToolTipText("Digite uma senha");

        ButSalvar.setBackground(new java.awt.Color(234, 234, 27));
        ButSalvar.setMnemonic('s');
        ButSalvar.setText("Salvar");
        ButSalvar.setToolTipText("Clique para salvar os dados");
        ButSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButSalvarActionPerformed(evt);
            }
        });

        ButCancelar.setBackground(new java.awt.Color(92, 92, 79));
        ButCancelar.setMnemonic('c');
        ButCancelar.setText("Cancelar");
        ButCancelar.setToolTipText("Clique para cancelar o cadastro");
        ButCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPTelaLoginLayout = new javax.swing.GroupLayout(jPTelaLogin);
        jPTelaLogin.setLayout(jPTelaLoginLayout);
        jPTelaLoginLayout.setHorizontalGroup(
            jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTelaLoginLayout.createSequentialGroup()
                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTelaLoginLayout.createSequentialGroup()
                                .addComponent(ButCancelar)
                                .addGap(12, 12, 12)
                                .addComponent(ButSalvar))
                            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLoginC, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCPF)
                                        .addComponent(jLabelDataNascimento)
                                        .addComponent(jLabelNome)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelSenha)
                                        .addGroup(jPTelaLoginLayout.createSequentialGroup()
                                            .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelCidade)
                                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(157, 157, 157)
                                            .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabelEstado)
                                                .addComponent(jCBEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                                .addComponent(jFmtDataNascimento)
                                .addGap(384, 384, 384)))
                        .addContainerGap())
                    .addGroup(jPTelaLoginLayout.createSequentialGroup()
                        .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefone)
                            .addComponent(jLabelLogin)
                            .addComponent(jFmtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPwdSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 414, Short.MAX_VALUE))))
        );
        jPTelaLoginLayout.setVerticalGroup(
            jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTelaLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPwdSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPTelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCancelar)
                    .addComponent(ButSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTelaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCancelarActionPerformed
        new Principal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButCancelarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void ButSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButSalvarActionPerformed
        int index = jCBEstados.getSelectedIndex();
        int jaexiste = 0;
        if(index == 0){
            JOptionPane.showMessageDialog(null, "Selecione um Estado.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);         
        }
        else if(txtNome.getText().equals("") | jFmtCPF.getText().equals("   .   .   -  ") | jFmtTelefone.getText().equals("(  )9    -    ") |
                txtCidade.getText().equals("") | txtLoginC.getText().equals("") |
                jPwdSenhaC.getText().equals("") | jFmtDataNascimento.getText().equals("  /  /    ")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de clicar em Salvar.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);         
        }
        else{
            String nome = txtNome.getText();
            String data = jFmtDataNascimento.getText();
            String cpf = jFmtCPF.getText();
            String cidade = txtCidade.getText();
            String estado = jCBEstados.getSelectedItem().toString();
            String telefone = jFmtTelefone.getText();
            String senha = jPwdSenhaC.getText();
            String login = txtLoginC.getText();
            for(int j = 0;j<users.size();j++){
                if(users.get(j).getLogin().equals(login)){
                    JOptionPane.showMessageDialog(null, "Já existe um usuário com esse login.", "Aviso!",
                JOptionPane.ERROR_MESSAGE);
                    jaexiste++;
                    break;
                }
            }
            if(jaexiste == 0){
                Random rand = new Random();
                Usuario user = new Usuario(cidade, telefone, nome, data, cpf, senha, login, rand.nextInt(10000));
                UsuarioDAO dao = new UsuarioDAO();
                dao.create(user);
                users.add(user);

                JOptionPane.showMessageDialog(null, "Usuário criado com sucesso.", "Aviso!",
                    JOptionPane.INFORMATION_MESSAGE);
                // Limpar os campos.
                txtNome.setText("");
                jFmtDataNascimento.setText("");
                jFmtCPF.setText("");
                txtCidade.setText("");
                jFmtTelefone.setText("");
                txtLoginC.setText("");
                jPwdSenhaC.setText("");

                txtNome.requestFocus();
            }
        }
        
    }//GEN-LAST:event_ButSalvarActionPerformed

    private void txtLoginCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginCActionPerformed

    private void jCBEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadosActionPerformed
        
    }//GEN-LAST:event_jCBEstadosActionPerformed

    private void jFmtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCancelar;
    private javax.swing.JButton ButSalvar;
    private javax.swing.JComboBox<String> jCBEstados;
    private javax.swing.JFormattedTextField jFmtCPF;
    private javax.swing.JFormattedTextField jFmtDataNascimento;
    private javax.swing.JFormattedTextField jFmtTelefone;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPTelaLogin;
    private javax.swing.JPasswordField jPwdSenhaC;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtLoginC;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
